<?php

/**
 * WP Arzo — AdminNeo WP-gated entry point.
 *
 * AdminNeo (adminneo.php) is bundled but **guarded**: it refuses to run unless the
 * constant WP_ARZO_ADMINNEO_OK is defined. This loader is the ONLY thing that
 * defines it, and only after bootstrapping WordPress and verifying the visitor is
 * an administrator. AdminNeo then auto-connects with the site's own DB credentials
 * (from wp-config), so admins get a full database manager without re-entering
 * credentials — but nobody unauthenticated can reach it.
 *
 * The plugin loads AdminNeo through an <iframe> pointing at THIS file, so AdminNeo's
 * own links/forms (which post back to this script) stay capability-gated on every
 * request via the WordPress auth cookie.
 *
 * @package WP_Arzo
 */

// Locate and boot WordPress (walk up from …/wp-content/plugins/wp-arzo/assets/libs/adminneo/).
$wp_arzo_dir = __DIR__;
$wp_arzo_load = '';
for ($wp_arzo_i = 0; $wp_arzo_i < 8; $wp_arzo_i++) {
    $wp_arzo_dir = dirname($wp_arzo_dir);
    if (file_exists($wp_arzo_dir . '/wp-load.php')) {
        $wp_arzo_load = $wp_arzo_dir . '/wp-load.php';
        break;
    }
}
if ($wp_arzo_load === '') {
    http_response_code(500);
    exit('WordPress could not be located.');
}
require_once $wp_arzo_load;

// Capability gate — the real authorization check, re-run on every AdminNeo request.
if (!function_exists('current_user_can') || !current_user_can('manage_options')) {
    http_response_code(403);
    exit('Forbidden — administrators only.');
}

// Respect the "Database" console-tool toggle.
if (function_exists('wp_arzo_console_tool_enabled') && !wp_arzo_console_tool_enabled('database')) {
    http_response_code(403);
    exit('The Database tool is disabled in WP Arzo → Advanced Tools.');
}

if (!file_exists(__DIR__ . '/adminneo.php')) {
    http_response_code(500);
    exit('AdminNeo library is not installed.');
}

// Build AdminNeo's config from WordPress's own DB credentials. Split DB_HOST into
// host / TCP port / Unix socket the same way the emergency tool does.
$wp_arzo_host = defined('DB_HOST') ? (string) DB_HOST : 'localhost';
$wp_arzo_port = '';
$wp_arzo_sock = '';
if ($wp_arzo_host !== '' && strpos($wp_arzo_host, ':') !== false) {
    list($wp_arzo_h, $wp_arzo_p) = explode(':', $wp_arzo_host, 2);
    $wp_arzo_host = $wp_arzo_h !== '' ? $wp_arzo_h : 'localhost';
    if (ctype_digit($wp_arzo_p)) {
        $wp_arzo_port = $wp_arzo_p;
    } elseif ($wp_arzo_p !== '') {
        $wp_arzo_sock = $wp_arzo_p;
    }
}
$wp_arzo_server = $wp_arzo_host;
if ($wp_arzo_port !== '') {
    $wp_arzo_server .= ':' . $wp_arzo_port;
} elseif ($wp_arzo_sock !== '') {
    $wp_arzo_server .= ':' . $wp_arzo_sock;
}
$wp_arzo_dbname = defined('DB_NAME') ? (string) DB_NAME : '';

$wp_arzo_cfg = array(
    'servers' => array(
        array(
            'driver'   => 'mysql',
            'server'   => $wp_arzo_server,
            'username' => defined('DB_USER') ? (string) DB_USER : '',
            'password' => defined('DB_PASSWORD') ? (string) DB_PASSWORD : '',
            'database' => $wp_arzo_dbname,
            'name'     => 'WordPress' . ($wp_arzo_dbname !== '' ? ' (' . $wp_arzo_dbname . ')' : ''),
        ),
    ),
    'defaultDriver'       => 'mysql',
    'defaultServer'       => $wp_arzo_server,
    'defaultDatabase'     => $wp_arzo_dbname,
    'defaultPasswordHash' => '', // passwordless: WordPress already authorized this admin
    'colorVariant'        => 'green',
);
@file_put_contents(
    __DIR__ . '/adminneo-config.php',
    "<?php\n// Auto-generated by WP Arzo from wp-config DB credentials. Regenerated each load.\nreturn " . var_export($wp_arzo_cfg, true) . ";\n"
);

// Unlock + run AdminNeo. CWD must be this dir so it reads adminneo-config.php.
// (AdminNeo's own login form is auto-submitted from the parent console page, which is not
// under AdminNeo's strict CSP — see features/database.php. The vendored adminneo.php has its
// X-Frame-Options relaxed to SAMEORIGIN so the WP-gated iframe can display it.)
if (!defined('WP_ARZO_ADMINNEO_OK')) {
    define('WP_ARZO_ADMINNEO_OK', true);
}
chdir(__DIR__);
require __DIR__ . '/adminneo.php';
exit;
